server:
  port: 8086

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
    password: 123456
  kafka:
    listener:
      concurrency: 5
    consumer:
      #是否自动提交偏移量
      enable-auto-commit: false
      group-id: test-group
      bootstrap-servers: 10.101.40.40:9092
#      bootstrap-servers: localhost:9092
      #指定消费策略(earliest|latest|none)
      auto-offset-reset: latest
      auto-commit-interval: 5000
      max-poll-records: 100
      max-poll-interval: 300000
      session-timeout: 150000
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
  task:
    pool:
      corePoolSize: 30
      maxPoolSize: 30
      keepAliveSeconds: 70
      queueCapacity: 25

#topic
kafka:
  app:
    topic:
      test1: TRIGGER_EVENTSYSTEM-TOPIC
      test2: test2
      test3: test3
  consumer:
    frequency: 20
    offset: true
    offsetTime: 2
