spring:
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-wait: 100000
        max-idle: 10
        max-active: 100
    timeout: 5000

redisson:
  lock:
    server:
      address: 127.0.0.1:6379
      type: standalone
      password:
      database: 1