spring:
  data:
    elasticsearch:
      cluster-name: elasticsearch
#      cluster-nodes: 127.0.0.1:9300
      cluster-nodes: 10.101.40.73:9300
      repositories:
        enabled: true
  elasticsearch:
    rest:
      uris: ["http://127.0.0.1:9200"]