server:
  port: 8083

oss:
  endpoint: oss-cn-shenzhen.aliyuncs.com
  keyid: LTAICo6hn8IO49m0 # 填写刚刚生成的AccessKey
  keysecret: A8cLCD97qc9NXGbtPKyc0QUz8zm98R  # 填写刚刚生成的Accesssecret
  bucketname: plat-common # bucket名称
  filehost: huolongguo    #bucket下文件夹的路径
  viewurl: http://plat-common.oss-cn-shenzhen.aliyuncs.com

spring:
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB