server:
  port: 8085

spring:
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://47.98.111.181:3307/studydb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
#    username: root
#    password: 123456
    # dynamic-datasource-spring-boot-starter 动态数据源的配置内容
    dynamic:
      primary: users # 设置默认的数据源或者数据源组，默认值即为 master
      datasource:
        # 订单 orders 数据源配置
        orders:
          url: jdbc:mysql://47.98.111.181:3307/studydb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 123456
        # 用户 users 数据源配置
        users:
          url: jdbc:mysql://47.98.111.181:3307/studydb?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
          driver-class-name: com.mysql.cj.jdbc.Driver
          username: root
          password: 123456